config/routes.rb
Rails.application.routes.draw do
  
  namespace :admins do
    get 'homes/top'
    resources :items, only: [:index,:new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :new, :create, :show, :edit, :update]
    resources :costomers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_items, only: [:update]
  end
  
     devise_for :admins, controllers: {
    sessions: "admins/sessions"
  }
   



 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  get "/about" => "homes#about", as: "about"
  

    
    root to: "homes#top"
    
    scope module: :public do
    devise_for :costomers
    
    resources :items, only: [:index, :show]
    
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    
    resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection do
        delete :destroy_all
      end
    end
    
    resources :orders, only: [:new, :create, :show, :index] do
      collection do
        post :confirm
        get :complete
      end
  
    end
    
     resources :order_items, only: [:create]
    
    resource :costomers, :path => "mypage", only: [:show, :edit, :update] do
      collection do
        get :resign
        patch :withdraw
      end
    
    end
     
   end
  
  
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :costomer
   
   def full_address
      "〒" + self.postal_code + "　" + self.address + "　" + self.name
   end
   
   def address_only
       "〒" + self.postal_code + "　" + self.address
   end
   
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :item
    belongs_to :costomer
    
     
    def add_tax_price
         (self.item.price * 1.08).round
    end
    
    #def subtotal_price
     #   (self.add_tax_price * cart_item.amount).round
    #end
end

app/models/costomer.rb
class Costomer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  
  validates :last_name, :last_name_kana, :first_name, :first_name_kana, :email, presence: true

  #boolean型の場合はenumではなくviewにif文で書く
  #enum is_active: { "有効":true, "退会":false}
  def full_address
    self.postal_code + self.address + self.last_name + self.first_name
  end
  
  def full_name
    self.last_name + self.first_name
  end
  
  def active_for_authentication?
    super && (self.is_active == true)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
    attachment :image
    
    belongs_to :genre
    has_many :cart_items, dependent: :destroy
    has_many :order_items, dependent: :destroy
    
    validates :name, presence: true
    validates :introduction, presence: true
    validates :price, presence: true
    
    def add_tax_price
         (self.price * 1.08).round
    end
    
    
    
    #boolean型の場合はenumではなくviewにif文で書く
   # enum is_active: {"販売中":true, "販売停止中":false}
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :costomer
    has_many :order_items, dependent: :destroy
    
    enum payment_method: { クレジットカード:0, 銀行振込:1 }
    enum order_received: { 入金待ち:0, 入金確認:1, 制作中:2, 発送準備中:3, 発送済み:4 }
    
    def shipping_cost
        800
    end
    
    def address_only
       "〒" + self.postal_code + "　" + self.address
    end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :item
    belongs_to :order
    
    enum production: { 着手不可:0, 製作待ち:1, 制作中:2, 制作完了:3 }
    
    def add_tax_price
         (self.price * 1.08).round
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    
  
   
    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys:[:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    
    def top
        @items = Item.limit(5).reverse_order
            
    end
    
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
end

app/helpers/admins/application_helper.rb
module Admins::ApplicationHelper
end

app/helpers/admins/costomers_helper.rb
module Admins::CostomersHelper
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admins_devise/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins_devise/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="vieport" content="with=devise-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
        <a class="nav-brand py-2" href="/"><%= image_tag("logo.png") %></a>
        <% if costomer_signed_in? %>
        <div class="name-box ml-5">
          <p>ようこそ <%= current_costomer.last_name %>さん！</p>
        </div>
        <% end %>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
 
        <ul class="navbar-nav ml-auto">
          <% if costomer_signed_in? %>
          <li>
            <%= link_to "マイページ", costomers_path, class:"nav-link" %>
          </li>
          <li>
            <%= link_to "商品一覧", items_path, class:"nav-link" %>
          </li>
          <li>
            <%= link_to "カート", cart_items_path, class:"nav-link" %>
          </li>
          <li>
            <%= link_to "ログアウト", destroy_costomer_session_path, method: :delete, class:"nav-link" %>
          </li>
          
          <% elsif admin_signed_in? %>
          <li>
           <%= link_to "商品一覧", admins_items_path, class:"nav-link" %>
          </li>
          <li>
            <%= link_to "会員一覧", admins_costomers_path, class:"nav-link" %>
          </li>
          <li>
            <%= link_to "注文履歴一覧", admins_homes_top_path, class:"nav-link" %>
          </li>
          <li>
            <%= link_to "ジャンル一覧", admins_genres_path, class:"nav-link" %>
          </li>
          <li>
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:"nav-link" %>
          </li>
          
          <% else %>
          <li>
            <%= link_to "About", about_path, class:"nav-link" %>
          </li>
          <li>
            <%= link_to "商品一覧", items_path, class:"nav-link" %>
          </li>
          <li>
            <%= link_to "新規登録", new_costomer_registration_path, class:"nav-link" %>
          </li>
          <li>
            <%= link_to "ログイン", new_costomer_session_path, class:"nav-link" %>
          </li>
          
        
          <% end %>
        </ul>
        
        </div>
        </div>
      </nav>
    </header>
    
    <main class="mt-5">
    <%= yield %>
    </main>
    
    <footer>
      <div class="container">
        <div class="row mt-">
          <div class="mx-auto mt-5">
            <p>CopyRight NaganoCake</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
  
</html>