config/routes.rb
Rails.application.routes.draw do
  
  namespace :admins do
    get 'homes/top'
    resources :items, only: [:index,:new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :new, :create, :show, :edit, :update]
    resources :costomers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_items, only: [:update]
  end
  
     devise_for :admins, controllers: {
    sessions: "admins/sessions"
  }
   



 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  get "/about" => "homes#about", as: "about"
  

    
    root to: "homes#top"
    
    scope module: :public do
    devise_for :costomers
    
    resources :items, only: [:index, :show]
    
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    
    resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection do
        delete :destroy_all
      end
    end
    
    resources :orders, only: [:new, :create, :show, :index] do
      collection do
        post :confirm
        get :complete
      end
  
    end
    
     resources :order_items, only: [:create]
    
    resource :costomers, :path => "mypage", only: [:show, :edit, :update] do
      collection do
        get :resign
        patch :withdraw
      end
    
    end
     
   end
  
  
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :costomer
   
   def full_address
      "〒" + self.postal_code + "　" + self.address + "　" + self.name
   end
   
   def address_only
       "〒" + self.postal_code + "　" + self.address
   end
   
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :item
    belongs_to :costomer
    
     
    def add_tax_price
         (self.item.price * 1.08).round
    end
    
    #def subtotal_price
     #   (self.add_tax_price * cart_item.amount).round
    #end
end

app/models/costomer.rb
class Costomer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  
  validates :last_name, :last_name_kana, :first_name, :first_name_kana, :email, presence: true

  #boolean型の場合はenumではなくviewにif文で書く
  #enum is_active: { "有効":true, "退会":false}
  def full_address
    self.postal_code + self.address + self.last_name + self.first_name
  end
  
  def full_name
    self.last_name + self.first_name
  end
  
  def active_for_authentication?
    super && (self.is_active == true)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
    attachment :image
    
    belongs_to :genre
    has_many :cart_items, dependent: :destroy
    has_many :order_items, dependent: :destroy
    
    validates :name, presence: true
    validates :introduction, presence: true
    validates :price, presence: true
    
    def add_tax_price
         (self.price * 1.08).round
    end
    
    
    
    #boolean型の場合はenumではなくviewにif文で書く
   # enum is_active: {"販売中":true, "販売停止中":false}
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :costomer
    has_many :order_items, dependent: :destroy
    
    enum payment_method: { クレジットカード:0, 銀行振込:1 }
    enum order_received: { 入金待ち:0, 入金確認:1, 制作中:2, 発送準備中:3, 発送済み:4 }
    
    def shipping_cost
        800
    end
    
    def address_only
       "〒" + self.postal_code + "　" + self.address
    end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :item
    belongs_to :order
    
    enum production: { 着手不可:0, 製作待ち:1, 制作中:2, 制作完了:3 }
    
    def add_tax_price
         (self.price * 1.08).round
    end
end

app/controllers/admins/costomers_controller.rb
class Admins::CostomersController < ApplicationController
    def index
        @costomers = Costomer.page(params[:page])
    end
    
    def show
        @costomer = Costomer.find(params[:id])
    end
    
    def edit
        @costomer = Costomer.find(params[:id])
    end
    
    def update
        @costomer = Costomer.find(params[:id])
        @costomer.update(costomer_params)
        redirect_to admins_costomer_path(@costomer.id)
    end
    
    
    protected
     def costomer_params
         params.require(:costomer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_active)
     end
    
end

app/controllers/admins/homes_controller.rb
class Admins::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).reverse_order
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    
  
   
    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys:[:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    
    def top
        @items = Item.limit(5).reverse_order
            
    end
    
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
end

app/helpers/admins/application_helper.rb
module Admins::ApplicationHelper
end

app/helpers/admins/costomers_helper.rb
module Admins::CostomersHelper
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/admins/order_items_helper.rb
module Admins::OrderItemsHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admins/costomers/edit.html.erb
<div class="container">
    <div class="row">
        <h3><%= @costomer.last_name %><%= @costomer.first_name %>さんの会員情報編集</h3>
    </div>
    
    <div class="row">
        <div class="col-md-10 offset-2">
            <%= form_with model: @costomer, url: admins_costomer_path, local:true do |f| %>
               <p>会員ID</p>
               <%= @costomer.id %>
     
               <p>名前</p>
              <div class="form-group">
              <label for="last_name">（姓）</label>
              <%= f.text_field :last_name, autofocus: true, class:"form-control col-sm-4"%>
              </div>
             
              <div class="form-group ">
              <label for="first_name">（名）</label>
              <%= f.text_field :first_name, autofocus: true, class:"form-control col-sm-4" %>
              </div>
            
        
             
               <p>フリガナ</p>
               
              <div class="form-group">
              <label for="last_name_kana">（セイ）</label>
              <%= f.text_field :last_name_kana, autofocus: true, class:"form-control"%>
              </div>
              <div class="form-group">
              <label for="first_name_kana">（メイ）</label>
              <%= f.text_field :first_name_kana, autofocus: true, class:"form-control" %>
              </div>
             
             <div class="form-group">
                 <label for="postal_code">郵便番号（ハイフンなし）</label>
                 <%= f.text_field :postal_code, autofocus: true, class:"form-control" %>
             </div>
             
             <div class="form-group">
                 <label for="address">住所</label>
                 <%= f.text_field :address, autofocus: true, class:"form-control" %>
             </div>
             
             <div class="form-group">
                 <label for="telephone_number">電話番号（ハイフンなし）</label>
                 <%= f.text_field :telephone_number, autofocus: true, class:"form-control" %>
             </div>
             
              <div class="form-group">
              <label for="email">メールアドレス</label>
              <%= f.email_field :email, autofocus: true, autocomplete: "email", class:"form-control" %>
             </div>
             <div class="form-group">
                 <label for= "is_active">会員ステータス</label>
                   <%= f.radio_button :is_active, :true %>
                   <%= f.label :is_active_true, '有効' %>
                   <%= f.radio_button :is_active, :false, class:"ml-3" %>
                   <%= f.label :is_active_false, '退会' %>
             </div>


             <div class="actions">
             <%= f.submit "編集する", class:"btn btn-success" %>
             </div>
          <% end %>
        </div>
    </div>
</div>

app/views/admins/costomers/index.html.erb
<div class="container">
    <div class="row">
        <h3>会員一覧</h3>
    </div>
    
    <div class="row">
        <div class="col-md-9 offset-2">
            <table class="table">
                <thead>
                    <tr>
                        <th>会員ID</th>
                        <th>氏名</th>
                        <th>メールアドレス</th>
                        <th>ステータス</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <% @costomers.each do |costomer| %>
                        <td><%= costomer.id %></td>
                        <td><%= link_to admins_costomer_path(costomer.id) do %>
                        <%=costomer.last_name %><%=costomer.first_name %>
                        <% end %></td>
                        <td><%=costomer.email %></td>
                        <td><%if costomer.is_active == true %>
                        <p class="text-success">有効</p>
                        <% else %>
                        <p>退会</p>
                        <% end %></td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
    
    <div class="row">
        <div class="mx-auto">
            <%= paginate @costomers %>
        </div>
    </div>
    
</div>

app/views/admins/costomers/show.html.erb
<div class="container">
    <div class="row">
        <h3><%= @costomer.last_name %><%= @costomer.first_name %>さんの会員詳細</h3>
    </div>
    <div class="row">
        <div class="costomer-box">
            <table>
                <tbody>
                    <tr></tr>
                    <tr>
                        <td>会員ID</td>
                        <td><%= @costomer.id %></td>
                    </tr>
                    <tr>
                        <td>氏名</td>
                        <td><%= @costomer.last_name %>　<%= @costomer.first_name %></td>
                    </tr>
                    <tr>
                        <td>フリガナ</td>
                        <td><%= @costomer.last_name_kana %>　<%= @costomer.first_name_kana %></td>
                    </tr>
                    <tr>
                        <td>郵便番号</td>
                        <td><%= @costomer.postal_code %></td>
                    </tr>
                    <tr>
                        <td>住所</td>
                        <td><%= @costomer.address %></td>
                    </tr>
                    <tr>
                        <td>電話番号</td>
                        <td><%= @costomer.telephone_number %></td>
                    </tr>
                    <tr>
                        <td>メールアドレス</td>
                        <td><%= @costomer.email %></td>
                    </tr>
                    <tr>
                        <td>会員ステータス</td>
                        <td><%if @costomer.is_active == true %>
                        <p class="text-success">有効</p>
                        <% else %>
                        <p>退会</p>
                        <% end %>
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td><%= link_to "編集する", edit_admins_costomer_path, class:"btn btn-success" %></td>
                        <td><%= link_to "注文履歴一覧を見る", admins_homes_top_path, class:"btn btn-primary" %></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>