config/routes.rb
Rails.application.routes.draw do
  
  namespace :admins do
    get 'homes/top'
    resources :items, only: [:index,:new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :new, :create, :show, :edit, :update]
    resources :costomers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_items, only: [:update]
  end
  
     devise_for :admins, controllers: {
    sessions: "admins/sessions"
  }
   



 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  get "/about" => "homes#about", as: "about"
  

    
    root to: "homes#top"
    
    scope module: :public do
    devise_for :costomers
    
    resources :items, only: [:index, :show]
    
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    
    resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection do
        delete :destroy_all
      end
    end
    
    resources :orders, only: [:new, :create, :show, :index] do
      collection do
        post :confirm
        get :complete
      end
  
    end
    
     resources :order_items, only: [:create]
    
    resource :costomers, :path => "mypage", only: [:show, :edit, :update] do
      collection do
        get :resign
        patch :withdraw
      end
    
    end
     
   end
  
  
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :costomer
   
   def full_address
      "〒" + self.postal_code + "　" + self.address + "　" + self.name
   end
   
   def address_only
       "〒" + self.postal_code + "　" + self.address
   end
   
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :item
    belongs_to :costomer
    
     
    def add_tax_price
         (self.item.price * 1.08).round
    end
    
    #def subtotal_price
     #   (self.add_tax_price * cart_item.amount).round
    #end
end

app/models/costomer.rb
class Costomer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  
  validates :last_name, :last_name_kana, :first_name, :first_name_kana, :email, presence: true

  #boolean型の場合はenumではなくviewにif文で書く
  #enum is_active: { "有効":true, "退会":false}
  def full_address
    self.postal_code + self.address + self.last_name + self.first_name
  end
  
  def full_name
    self.last_name + self.first_name
  end
  
  def active_for_authentication?
    super && (self.is_active == true)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
    attachment :image
    
    belongs_to :genre
    has_many :cart_items, dependent: :destroy
    has_many :order_items, dependent: :destroy
    
    validates :name, presence: true
    validates :introduction, presence: true
    validates :price, presence: true
    
    def add_tax_price
         (self.price * 1.08).round
    end
    
    
    
    #boolean型の場合はenumではなくviewにif文で書く
   # enum is_active: {"販売中":true, "販売停止中":false}
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :costomer
    has_many :order_items, dependent: :destroy
    
    enum payment_method: { クレジットカード:0, 銀行振込:1 }
    enum order_received: { 入金待ち:0, 入金確認:1, 制作中:2, 発送準備中:3, 発送済み:4 }
    
    def shipping_cost
        800
    end
    
    def address_only
       "〒" + self.postal_code + "　" + self.address
    end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :item
    belongs_to :order
    
    enum production: { 着手不可:0, 製作待ち:1, 制作中:2, 制作完了:3 }
    
    def add_tax_price
         (self.price * 1.08).round
    end
end

app/controllers/admins/homes_controller.rb
class Admins::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).reverse_order
  end
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
    
    def index
        @items = Item.page(params[:page])
    end
    
    def new
        @item = Item.new
    end
    
    def create
        @item = Item.new(item_params)
        if @item.save
           redirect_to admins_item_path(@item.id)
        else
            render :new
        end
    end
    
    def show
        @item = Item.find(params[:id])
    end
    
    def edit
        @item = Item.find(params[:id])
    end
    
    def update
        @item = Item.find(params[:id])
        @item.update(item_params)
        redirect_to admins_item_path(@item.id)
    end
    
    protected
    
    def item_params
        params.require(:item).permit(:name, :image, :introduction, :price, :is_active, :genre_id)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    
  
   
    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys:[:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    
    def top
        @items = Item.limit(5).reverse_order
            
    end
    
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
end

app/helpers/admins/application_helper.rb
module Admins::ApplicationHelper
end

app/helpers/admins/costomers_helper.rb
module Admins::CostomersHelper
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/admins/order_items_helper.rb
module Admins::OrderItemsHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admins/items/edit.html.erb
<div class="container">
    <div class="row">
        <div class="form-title">
            <h2>商品編集</h2>
        </div>
    </div>
    
    <div class="row">
        <div class="text-danger">
          <% if @item.errors.any? %>
          <%= @item.errors.count %>件のエラーが発生しました</br>
          <% @item.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
          <% end %>
        </div>
    </div>
    
    <div class="row">
        <div class="form-box">
            <%= form_with model: @item, url: admins_item_path(@item.id), local:true do |f| %>
            
            <div class="form-group">
                <label for="image_">商品画像</label>
                <%= f.attachment_field :image %>
            </div>
            <div class="form-group">
                <label for="name">商品名</label>
                <%= f.text_field :name %>
            </div>
            <div class="form-group">
                <label for="introduction">商品説明</label>
                <%= f.text_area :introduction %>
            </div>
            <div class="form-group">
                <lavel for="genre_id">ジャンル</lavel>
                <%= f.collection_select :genre_id, Genre.all, :id, :name, :prompt =>"ジャンルを選択" %>
            </div>
            <div class="form_group">
                <label for="price">税抜価格</label>
                <%= f.text_field :price %>円
            </div>
            <div class="form_group">
                <label for="is_active">販売ステータス</label>
               <%= f.radio_button :is_active, :true %>
               <%= f.label :is_active_true, '販売中' %>
               <%= f.radio_button :is_active, :false, class:"ml-3" %>
               <%= f.label :is_active_false, '販売停止中' %>
            </div>
            <div class="action">
                <%= f.submit "編集する", class:"btn btn-success" %>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/admins/items/index.html.erb
<div class="container">
    <div class="row">
        <h3>商品一覧</h3>
        <%= link_to "＋", new_admins_item_path, class:"btn-primary rounded-circle p-0 ml-5" %>
    </div>
    <div class="row">
        <div class="items-box">
            <table class="table">
                <thead>
                    <tr>
                        <th>商品ID</th>
                        <th>商品名</th>
                        <th>税抜価格</th>
                        <th>ジャンル</th>
                        <th>販売ステータス</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <% @items.each do |item| %>
                        <td>
                            <%= item.id %>
                        </td>
                        <td>
                            <%= link_to admins_item_path(item.id) do %><%= item.name %><% end %>
                        </td>
                        <td>
                            <%= item.price %>
                        </td>
                        <td>
                            <%= item.genre.name %>
                        </td>
                        <td>
                            <% if item.is_active == true %>
                            <p class="text-success">販売中</p>
                            <% else %>
                            <p>販売停止中</p>
                            <% end %>
                        </td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
    
    <div class="row">
        <div class="mx-auto">
            <%= paginate @items %>
        </div>
    </div>
</div>

app/views/admins/items/new.html.erb
<div class="container">
    <div class="row">
        <div class="form-title">
            <h2>新規商品登録</h2>
        </div>
    </div>
    
    <div class="row">
        <div class="text-danger">
          <% if @item.errors.any? %>
          <%= @item.errors.count %>件のエラーが発生しました</br>
          <% @item.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
          <% end %>
        </div>
    </div>
   
    
    <div class="row">
        <div class="form-box">
            <%= form_with model: @item, url: admins_items_path, local:true do |f| %>
            
            <div class="form-group">
                <label for="image_">商品画像</label>
                <%= f.attachment_field :image %>
            </div>
            <div class="form-group">
                <label for="name">商品名</label>
                <%= f.text_field :name %>
            </div>
            <div class="form-group">
                <label for="introduction">商品説明</label>
                <%= f.text_area :introduction %>
            </div>
            <div class="form-group">
                <lavel for="genre_id">ジャンル</lavel>
                <%= f.collection_select :genre_id, Genre.all, :id, :name, :prompt =>"ジャンルを選択" %>
            </div>
            <div class="form_group">
                <label for="price">税抜価格</label>
                <%= f.text_field :price %>円
            </div>
            <div class="form_group">
                <label for="is_active">販売ステータス</label>
               <%= f.radio_button :is_active, :true %>
               <%= f.label :is_active_true, '販売中' %>
               <%= f.radio_button :is_active, :false, class:"ml-3" %>
               <%= f.label :is_active_false, '販売停止中' %>
              </div>
            <div class="action">
                <%= f.submit "新規登録", class:"btn btn-success" %>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/admins/items/show.html.erb
<div class="container">
    <div class="row">
        <h2>商品詳細</h2>
    </div>
    
    <div class="row">
        <div class="col-md-3">
            <%= attachment_image_tag @item, :image, :fill, 200,200 %>
        </div>
        <div class="col-md-8 offset-1">
            <div class="item-body">
                <table>
                    <tbody>
                        <tr>
                            <td>商品名</td>
                                <td>
                                    <%= @item.name %>
                                </td>
                        </tr>
                        <tr>
                            <td>商品説明</td>
                            <td>
                                <%= @item.introduction %>
                            </td>
                        </tr>
                        <tr>
                            <td>ジャンル</td>
                            <td>
                                <%= @item.genre.name %>
                            </td>
                        </tr>
                        <tr>
                            <td>
                               税込価格</br>
                                (税抜価格）
                                </td>
                            <td>
                                <%= @item.add_tax_price.to_s(:delimited) %>　(<%= @item.price %>)円
                            </td>
                            
                        </tr>
                        <tr>
                            <td>販売ステータス</td>
                            <td>
                                <%if @item.is_active == true %>
                                <p class="text-success">販売中</p>
                                <% else %>
                                <p>販売停止中</p>
                                <% end %>
                            </td>
                        </tr>
                        <tr>
                            <td><%= link_to "編集する", edit_admins_item_path, class:"btn btn-success" %></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>