config/routes.rb
Rails.application.routes.draw do
  
  namespace :admins do
    get 'homes/top'
    resources :items, only: [:index,:new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :new, :create, :show, :edit, :update]
    resources :costomers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_items, only: [:update]
  end
  
     devise_for :admins, controllers: {
    sessions: "admins/sessions"
  }
   



 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  get "/about" => "homes#about", as: "about"
  

    
    root to: "homes#top"
    
    scope module: :public do
    devise_for :costomers
    
    resources :items, only: [:index, :show]
    
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    
    resources :cart_items, only: [:index, :update, :create, :destroy] do
      collection do
        delete :destroy_all
      end
    end
    
    resources :orders, only: [:new, :create, :show, :index] do
      collection do
        post :confirm
        get :complete
      end
  
    end
    
     resources :order_items, only: [:create]
    
    resource :costomers, :path => "mypage", only: [:show, :edit, :update] do
      collection do
        get :resign
        patch :withdraw
      end
    
    end
     
   end
  
  
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :costomer
   
   def full_address
      "〒" + self.postal_code + "　" + self.address + "　" + self.name
   end
   
   def address_only
       "〒" + self.postal_code + "　" + self.address
   end
   
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :item
    belongs_to :costomer
    
     
    def add_tax_price
         (self.item.price * 1.08).round
    end
    
    #def subtotal_price
     #   (self.add_tax_price * cart_item.amount).round
    #end
end

app/models/costomer.rb
class Costomer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  
  validates :last_name, :last_name_kana, :first_name, :first_name_kana, :email, presence: true

  #boolean型の場合はenumではなくviewにif文で書く
  #enum is_active: { "有効":true, "退会":false}
  def full_address
    self.postal_code + self.address + self.last_name + self.first_name
  end
  
  def full_name
    self.last_name + self.first_name
  end
  
  def active_for_authentication?
    super && (self.is_active == true)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
    attachment :image
    
    belongs_to :genre
    has_many :cart_items, dependent: :destroy
    has_many :order_items, dependent: :destroy
    
    validates :name, presence: true
    validates :introduction, presence: true
    validates :price, presence: true
    
    def add_tax_price
         (self.price * 1.08).round
    end
    
    
    
    #boolean型の場合はenumではなくviewにif文で書く
   # enum is_active: {"販売中":true, "販売停止中":false}
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :costomer
    has_many :order_items, dependent: :destroy
    
    enum payment_method: { クレジットカード:0, 銀行振込:1 }
    enum order_received: { 入金待ち:0, 入金確認:1, 制作中:2, 発送準備中:3, 発送済み:4 }
    
    def shipping_cost
        800
    end
    
    def address_only
       "〒" + self.postal_code + "　" + self.address
    end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :item
    belongs_to :order
    
    enum production: { 着手不可:0, 製作待ち:1, 制作中:2, 制作完了:3 }
    
    def add_tax_price
         (self.price * 1.08).round
    end
end

app/controllers/admins/genres_controller.rb
class Admins::GenresController < ApplicationController
    
    def index
        @genres = Genre.all
        @genre = Genre.new
    end
    
    def create
        @genre =Genre.new(genre_params)
        @genre.save
        redirect_to admins_genres_path
    end
    
    def edit
        @genre = Genre.find(params[:id])
    end
    
    def update
        @genre = Genre.find(params[:id])
        @genre.update(genre_params)
        redirect_to admins_genres_path
    end
    
    private
    def genre_params
        params.require(:genre).permit(:name)
    end
    
end

app/controllers/admins/homes_controller.rb
class Admins::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).reverse_order
  end
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
    
    def index
        @items = Item.page(params[:page])
    end
    
    def new
        @item = Item.new
    end
    
    def create
        @item = Item.new(item_params)
        if @item.save
           redirect_to admins_item_path(@item.id)
        else
            render :new
        end
    end
    
    def show
        @item = Item.find(params[:id])
    end
    
    def edit
        @item = Item.find(params[:id])
    end
    
    def update
        @item = Item.find(params[:id])
        @item.update(item_params)
        redirect_to admins_item_path(@item.id)
    end
    
    protected
    
    def item_params
        params.require(:item).permit(:name, :image, :introduction, :price, :is_active, :genre_id)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    
  
   
    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys:[:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    
    def top
        @items = Item.limit(5).reverse_order
            
    end
    
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
end

app/helpers/admins/application_helper.rb
module Admins::ApplicationHelper
end

app/helpers/admins/costomers_helper.rb
module Admins::CostomersHelper
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/admins/order_items_helper.rb
module Admins::OrderItemsHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admins/homes/top.html.erb
<div class="cotainer mx-5">
    <div class="row">
        <h4>注文履歴一覧</h4>
    </div>
    <div class="row">
        <table class="table">
            <thead>
                <tr class="table-active">
                    <th>購入日時</th>
                    <th>購入者</th>
                    <th>注文個数</th>
                    <th>注文ステータス</th>
                </tr>
            </thead>
            <tbody>
                <% @orders.each do |order| %>
                <tr>
                    <td><%= link_to admins_order_path(order.id) do %>
                        <%= order.created_at.strftime("%y-%m-%d %H:%M") %>
                        <% end %>
                    </td>
                    <td><%= order.costomer.full_name %></td>
                    <td><%= order.order_items.count %></td>
                    <td><%= order.order_received %></td>
                </tr>
                <% end %>
               
            </tbody>
        </table>
         
    </div>
    <div class="row">
        <div class="mx-auto">
            <%= paginate @orders %>
        </div>
        
    </div>
    
</div>

app/views/homes/about.html.erb
<div class="container sm-12 md-8 lg-5 px-5 px-sm-0">
    <div class="row">
        
    　<div class="about-box text-center mx-auto">
            <h1>About</h1>
            
        <div class="introduction">
            <p>ながのCAKEは全国発送可能なケーキ屋さんです。</p>
            <p>お子様からお年寄りの方までお召し上がりいただけるよう、</p>
            <p>様々なバリエーションをご用意しております。</p>
            <p>また、全国発送可能ですので、「いつ」でも「どこ」でもご注文いただけます。</p>
            <p>ぜひご注文ください。</p>
        </div>
        
        <div class="about-image">
            <%= image_tag('about.jpg')%>
        </div>
      </div>
        
    </div>
</div>

app/views/homes/top.html.erb
<div class="container sm-12 md-8 lg-5 px-5 px-sm-0">
    <div class="row">
        
     <div class="top-text-box col-md-8 mx-auto mb-0">
      <h4 class="text-light">ようこそ<stromg>ながのCAKE</stromg>へ！</h3>
      
        <p class="text-light">
          このサイトは、ケーキ販売のECサイトになります。<br>
          会員でない方も商品の閲覧はできますが、</br>
          購入には会員登録が必要になります。
        </p>
        
     </div>
     
    </div>
    <div class="row mt-5">
        
        <div class="new-items mx-auto">
            
            <h4>新着商品</h4>
            
            <div class="items-box d-flex">
            <% @items.each do |item| %>
            <% if item.is_active? %>
             <div class="item-box d-inline-block ml-3">
                <%= link_to item_path(item.id) do %><%= attachment_image_tag item, :image, :fill, 150, 150 %><% end %></br>
                <%= link_to item_path(item.id) do %><%= item.name %><% end %></br>
                <p>¥<%= item.add_tax_price.to_s(:delimited) %>円</p>
            </div>
            <% end %>
            <% end %>
            </div>
        </div>
        
    </div>
</div>